[platformio]
default_envs = esp-hi-c3

[env:esp-hi-c3]
platform = espressif32@6.12.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
